### ISSUE TITLE
Some unauthenticated ES requests

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4739]
```
[2023-03-06T09:42:19,194][WARN ][o.o.s.a.BackendRegistry  ] [test-cos01-nd03-pri.servicemss.sante-ra.fr] No 'Authorization' header, send 401 and 'WWW-Authenticate Basic'
[2023-03-06T09:42:19,808][WARN ][o.o.s.a.BackendRegistry  ] [test-cos01-nd03-pri.servicemss.sante-ra.fr] No 'Authorization' header, send 401 and 'WWW-Authenticate Basic'
```

This do not cause runtime defects.

I do think this is on;y the first call to OpenSearch. Then JAMES relaunches the call with login informations.

If that is well the behaviour described, then maybe there's a risk for performances.

Worth investigations...

**Comment by chibenwa** [comment]
[opensearch-config.zip](https://github.com/linagora/james-project/files/10916320/opensearch-config.zip)

Docker-compose:

```
version: '3'
services:
  opensearch-node:
    image: sara/opensearch:2.6.0
    container_name: test-cos01-nd01-pri.servicemss.sante-ra.fr
    hostname: test-cos01-nd01-pri.servicemss.sante-ra.fr
    environment:
      - cluster.name=testcos01
      - node.name=test-cos01-nd01-pri.servicemss.sante-ra.fr
      - discovery.seed_hosts=10.200.22.160,10.200.22.161,10.200.22.162
      - cluster.initial_cluster_manager_nodes=10.200.22.160,10.200.22.161,10.200.22.162
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms4g -Xmx4g" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - "DISABLE_INSTALL_DEMO_CONFIG=true" # disables execution of install_demo_configuration.sh bundled with security plugin, which installs demo certificates and security configurations to OpenSearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - ./config/opensearch-config:/usr/share/opensearch/config
      - ./config/tls:/usr/share/opensearch/config/tls
      - ./data:/usr/share/opensearch/data
      - ./backup:/backup
    network_mode: "host"    
```
